### ISSUE TITLE
Please be patient.

### ISSUE THREAD

**Issue by lukebakken** [AdirthaBorgohain/rabbitmq-examples#1]
I am returning to work today and will try to find time to assist this week.

https://stackoverflow.com/q/72792217/1466825

**Comment by AdirthaBorgohain** [comment]
My apologies, sorry. Thought you could have missed out on it due to your busy schedule.

**Comment by lukebakken** [comment]
Please see my fork here:

https://github.com/lukebakken/rabbitmq-examples

I will open an issue there so we can discuss these scripts:

https://github.com/lukebakken/rabbitmq-examples/blob/master/consumer.py
https://github.com/lukebakken/rabbitmq-examples/blob/master/lrb-publisher.py
